"""empty message

Revision ID: 02e15b7e0013
Revises: d26feb2b3fde
Create Date: 2016-05-11 12:11:47.981244

"""

# revision identifiers, used by Alembic.
revision = '02e15b7e0013'
down_revision = 'd26feb2b3fde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    ### end Alembic commands ###
