"""empty message

Revision ID: f7600f862e03
Revises: 02e15b7e0013
Create Date: 2016-05-12 17:38:42.044363

"""

# revision identifiers, used by Alembic.
revision = 'f7600f862e03'
down_revision = '02e15b7e0013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
